#
# Exporter settings
#

# Enable debug mode
# debug: false

# Log format (text or json)
# log-format: json

# Path under which to expose metrics
# metrics-path: /metrics

# Address to listen on for web interface
# listen-address: ":9043"

# Path to TLS certificate
# tls-cert-path: ""

# Path to private key for TLS
# tls-key-path: ""

# Enable OpenTelemetry traces
# See https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter for configuration parameters
# enable-otel-traces: true

#
# AWS credentials
#

# AWS IAM ARN role to assume to fetch metrics
# aws-assume-role-arn: arn:aws:iam::000000000000:role/prometheus-rds-exporter

# AWS assume role session name
# aws-assume-role-session: prometheus-rds-exporter

#
# Metrics
#

# Collect AWS instances metrics (AWS Cloudwatch API)
# collect-instance-metrics: true

# Collect AWS instance tags (AWS RDS API)
# collect-instance-tags: true

# Collect AWS instance types information (AWS EC2 API)
# collect-instance-types: true

# Collect AWS instances logs size (AWS RDS API)
# collect-logs-size: true

# Collect AWS instances maintenances (AWS RDS API)
# collect-maintenances: true

# Collect AWS RDS quotas (AWS quotas API)
# collect-quotas: true

# Collect AWS RDS usages (AWS Cloudwatch API)
# collect-usages: true

# Select AWS instances by tags
# tag-selections:
#   Environment:
#   - staging